# Generated by Django 5.1.7 on 2025-04-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_verification_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
