# Generated by Django 5.1.7 on 2025-04-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_last_verification_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
