# Generated by Django 5.1.7 on 2025-04-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='info',
            field=models.CharField(max_length=255),
        ),
    ]
