# Generated by Django 5.1.7 on 2025-05-01 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pendingemailchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='date',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
