# Generated by Django 5.1.7 on 2025-05-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_projects',
            field=models.ManyToManyField(related_name='project_examples', to='api.projects'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_skills',
            field=models.ManyToManyField(related_name='acquired_skills', to='api.skills'),
        ),
    ]
