# Generated by Django 5.1.7 on 2025-05-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_courses_course_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='job_title',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
