# Generated by Django 5.1.7 on 2025-05-03 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_courses_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graduation_date', to='api.dates'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='end_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_date', to='api.dates'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='start_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_date', to='api.dates'),
        ),
    ]
