# Generated by Django 5.1.7 on 2025-05-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_education_graduation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='date',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
