# Generated by Django 5.1.7 on 2025-05-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_education_graduation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='generaluserinfo',
            name='spoken_languages',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='features',
        ),
    ]
