# Generated by Django 5.1.7 on 2025-05-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_employment_responsibilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='generaluserinfo',
            name='spoken_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projects',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
