# Generated by Django 5.1.7 on 2025-06-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_employment_responsibilities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaluserinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
