# Generated by Django 5.1.7 on 2025-06-02 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20250603_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluserinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_user_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
