# Generated by Django 5.1.7 on 2025-06-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_generaluserinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, unique=True)),
                ('language_self_name', models.CharField(max_length=50, unique=True)),
                ('cv_summary', models.CharField(max_length=50)),
                ('cv_skills', models.CharField(max_length=50)),
                ('cv_projects', models.CharField(max_length=50)),
                ('cv_experience', models.CharField(max_length=50)),
                ('cv_certifications', models.CharField(max_length=50)),
                ('cv_education', models.CharField(max_length=50)),
                ('cv_languages', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
