# Generated by Django 5.1.7 on 2025-06-05 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.JSONField(blank=True, default=list)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_language', to='api.languages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_projects',
            field=models.ManyToManyField(related_name='course_projects', to='api.projectexamples'),
        ),
    ]
