# Generated by Django 5.1.7 on 2025-06-06 19:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_projectexamples_alter_courses_course_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveSmallIntegerField()),
                ('stage_title', models.CharField(max_length=100)),
                ('years_from', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('years_to', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(30)])),
                ('goal', models.CharField(max_length=255)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('job_titles', models.JSONField(blank=True, default=list)),
                ('learning_paths', models.JSONField(blank=True, default=list)),
                ('recommended_projects', models.JSONField(blank=True, default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_stages', to='api.courses')),
            ],
            options={
                'ordering': ['stage_number'],
                'unique_together': {('course', 'stage_number')},
            },
        ),
    ]
